name: angel_note
dependencies:
  angel_common: ^1.0.0 # Installs the main framework, along with several commonly-used Angel packages
  angel_security: ^1.0.0 # Includes security functionality, as well as generic authorization hooks
  angular2: ^3.0.0
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.0
transformers:
  - angular2:
      platform_directives:
        - 'package:angular2/common.dart#COMMON_DIRECTIVES'
      platform_pipes:
        - 'package:angular2/common.dart#COMMON_PIPES'
      entry_points:
        - web/main.dart
  - dart_to_js_script_rewriter